### ISSUE TITLE
Update gear menu for classic

### ISSUE THREAD

**Issue by nabriis** [RagedUnicorn/wow-vanilla-gearmenu#16]
This addon should be updated for classic! I wonder if the quick change rules would work with the legion addon API though.

**Comment by RagedUnicorn** [comment]
Hi @nabriis I will definitely update the Addon for classic at one point. I'm not sure when exactly because I don't have access to beta and once it is released I will probably be quite occupied :)

Cheers,
RagedUnicorn

**Comment by ujellyx** [comment]
Looking forward to an update aswell! This addon is so convenient :) especially for Hunters.
