### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by shikulja** [RagedUnicorn/wow-vanilla-gearmenu#17]
will there be a new release?
after 1.2.1 corrections were released, but there is no release, and the master branch with debug mode.
I'd like to fix the add-on translation for the latest fixes.

**Comment by RagedUnicorn** [comment]
Hi,

There is currently no new release planned for the addon. See https://github.com/RagedUnicorn/wow-classic-gearmenu for a wow classic version of the addon.

Regards,
RagedUnicorn
