### ISSUE TITLE
ru Translation and some notes

### ISSUE THREAD

**Issue by shikulja** [RagedUnicorn/wow-vanilla-gearmenu#18]
Gear Menu ru Translation (for lastest  commit)
[GearMenuRUS.zip](https://github.com/RagedUnicorn/wow-vanilla-gearmenu/files/3919720/GearMenuRUS.zip)

also a few notes
1. need to add the word "None" to the translation file.
![Скриншот 04-12-2019 050727](https://user-images.githubusercontent.com/3386359/70106248-1f838b80-1654-11ea-863c-ce82f0133795.png)

2.the text does not fit into the frame.
The translation of words is done very accurately, the maximum number of characters is 25.
![Скриншот 04-12-2019 050747](https://user-images.githubusercontent.com/3386359/70106249-1f838b80-1654-11ea-9cac-fcb13639fa4f.png)

3. I get an error, it is not related to the translation. But .. she is. Because of what I do not know.

when you turn on the option - small tooltips, and when you hover over any item the game starts reporting an error

TinyTip is possible, or other add-ons that add more information, I attach the image of the error, maybe this will help to fix it someday.

- works
![Скриншот 04-12-2019 052016](https://user-images.githubusercontent.com/3386359/70106921-08de3400-1656-11ea-99e7-133503c216fd.png)

- not works (after enabling the option of small tooltips)
![Скриншот 04-12-2019 052056](https://user-images.githubusercontent.com/3386359/70106931-17c4e680-1656-11ea-862d-ead8c56e721b.png)

**Comment by RagedUnicorn** [comment]
Hi @shikulja 

I do no longer support this version of the GearMenu addon. You are however welcome to add this translation to classic version. See - https://github.com/RagedUnicorn/wow-classic-gearmenu

Cheers,
RagedUnicorn
