### ISSUE TITLE
GearMenu apparently doesnt work with custom bags

### ISSUE THREAD

**Issue by AdmiralAwsum** [RagedUnicorn/wow-vanilla-gearmenu#20]
Gearmenu doesnt work with big 36 bags that are custom made on Turtle WoW server. Can you add support for this?

Issue is that you can see the items you want to swap to in GearMenu, but when you click them nothing happens.

**Comment by RagedUnicorn** [comment]
Hi @AdmiralAwsum,

I'm not sure I can help much. I never played Turtle WoW and I don't know what kind of API they use. I often hear that those custom servers are using a WOTLK client and modify it (not sure though).

GearMenu itself figures out the Size of any bag by using `GetContainerNumSlots`

You should be able to try this out yourself by using the following command.

```
/dump GetContainerNumSlots(0)
# if dump doesn't work try the following
/run print(GetContainerNumSlots(0))
```

Replace the number with the position of the bag. It starts with 0 and goes up to 4.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Closing this. Please reopen if you have any new details for me to checkout
